[package]
name = "imgpress"
version = "0.1.0"
edition = "2021"
rust-version = "1.92"

[lib]
name = "imgpress"
path = "src/lib.rs"

[[bin]]
name = "imgpress"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
eframe = { version = "0.35.0", default-features = false, features = ["default_fonts", "glow"] }
egui = "0.35.0"
rfd = "0.17.2"
open = "5.4.0"

image = { version = "0.25", default-features = false, features = ["jpeg", "png", "ico"] }
webp = "0.3"
mupdf = { version = "0.8", default-features = false, features = ["img", "base14-fonts"] }

rayon = "1.10"
crossbeam-channel = "0.5"

thiserror = "2.0.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
directories = "6.0.0"
log = "0.4"
env_logger = "0.11"

[target.'cfg(not(target_os = "windows"))'.dependencies]
wayland-sys = "0.31"

[build-dependencies]
embed-resource = "3.0.11"

[patch.crates-io]
mupdf = { path = "patch/mupdf" }

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1